modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="pvp_additions"
version="1.0.0"
displayName="PvP Additions"
credits="https://discord.gg/zPxVc6x2Y6"
displayURL="https://discord.gg/zPxVc6x2Y6"
updateJSONURL="https://discord.gg/zPxVc6x2Y6"
logoFile="logo.png"
authors="The_WereF0X"
description="PvP Additons. Check Modrinth/CurseForge/Discord for wiki."

[[dependencies.pvp_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




